/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Mode = IDL.Variant({
  'exam' : IDL.Null,
  'fast' : IDL.Null,
  'learn' : IDL.Null,
  'build' : IDL.Null,
});
export const Topic = IDL.Record({
  'mode' : Mode,
  'text' : IDL.Text,
  'description' : IDL.Text,
  'response' : IDL.Text,
});

export const idlService = IDL.Service({
  'addFavorite' : IDL.Func([IDL.Text], [], []),
  'addTopic' : IDL.Func([IDL.Text, IDL.Text, Mode, IDL.Text], [], []),
  'getFavorites' : IDL.Func([], [IDL.Vec(Topic)], ['query']),
  'getProgress' : IDL.Func([], [IDL.Nat], ['query']),
  'getTopicHistory' : IDL.Func([], [IDL.Vec(Topic)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Mode = IDL.Variant({
    'exam' : IDL.Null,
    'fast' : IDL.Null,
    'learn' : IDL.Null,
    'build' : IDL.Null,
  });
  const Topic = IDL.Record({
    'mode' : Mode,
    'text' : IDL.Text,
    'description' : IDL.Text,
    'response' : IDL.Text,
  });
  
  return IDL.Service({
    'addFavorite' : IDL.Func([IDL.Text], [], []),
    'addTopic' : IDL.Func([IDL.Text, IDL.Text, Mode, IDL.Text], [], []),
    'getFavorites' : IDL.Func([], [IDL.Vec(Topic)], ['query']),
    'getProgress' : IDL.Func([], [IDL.Nat], ['query']),
    'getTopicHistory' : IDL.Func([], [IDL.Vec(Topic)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };