/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Mode = { 'exam' : null } |
  { 'fast' : null } |
  { 'learn' : null } |
  { 'build' : null };
export interface Topic {
  'mode' : Mode,
  'text' : string,
  'description' : string,
  'response' : string,
}
export interface _SERVICE {
  'addFavorite' : ActorMethod<[string], undefined>,
  'addTopic' : ActorMethod<[string, string, Mode, string], undefined>,
  'getFavorites' : ActorMethod<[], Array<Topic>>,
  'getProgress' : ActorMethod<[], bigint>,
  'getTopicHistory' : ActorMethod<[], Array<Topic>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];